In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler

In [2]:
ratings = pd.read_csv(r'C:\Users\adity\Documents\Machine Learning\Recommendation\DataSets\Movie1\ratings.csv')
ratings.head(10)

user_id  movie_id  rating   timestamp
0      172     94969     5.0  1396067836
1      172     98956     4.0  1396067879
2      176     73881     4.0  1499807147
3      221      1900     4.5  1288550866
4      333     33688     4.0  1412015122
5      333     78408     2.0  1412015747
6      333     81111     3.0  1412015924
7      333     94190     5.0  1412016036
8      339    167038     0.5  1527515624
9      422     64650     5.0  1529609466

In [3]:
movies = pd.read_csv(r'C:\Users\adity\Documents\Machine Learning\Recommendation\DataSets\Movie1\titles.csv')
movies.head(10)

movie_id                                              title
0       139                                      Target (1995)
1       568                          Bhaji on the Beach (1993)
2      1900  Children of Heaven  The (Bacheha-Ye Aseman) (1...
3      2284                                Bandit Queen (1994)
4      5985                    Asoka (Ashoka the Great) (2001)
5      6244                              Salaam Bombay! (1988)
6      6674               War and Peace (Jang Aur Aman) (2001)
7      6683                                        Fire (1996)
8      8971                                  Veer Zaara (2004)
9     27131                                      Dil Se (1998)

In [4]:
df = pd.merge(ratings, movies, how='left', on='movie_id')
df.head(10)

user_id  movie_id  rating   timestamp  \
0      172     94969     5.0  1396067836   
1      172     98956     4.0  1396067879   
2      176     73881     4.0  1499807147   
3      221      1900     4.5  1288550866   
4      333     33688     4.0  1412015122   
5      333     78408     2.0  1412015747   
6      333     81111     3.0  1412015924   
7      333     94190     5.0  1412016036   
8      339    167038     0.5  1527515624   
9      422     64650     5.0  1529609466   

                                               title  
0                                     Kahaani (2012)  
1                                      Barfi! (2012)  
2                                    3 Idiots (2009)  
3  Children of Heaven  The (Bacheha-Ye Aseman) (1...  
4                                   Parineeta (2005)  
5                               Salaam-E-Ishq (2007)  
6                                 Peepli Live (2010)  
7                                     Aakrosh (2010)  
8                                Dear Zindagi (2016)  
9  Marriage Made in Heaven  A (Rab Ne Bana Di Jod...

In [ ]:
df.shape

(17604, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17604 entries, 0 to 17603
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   user_id    17604 non-null  int64  
 1   movie_id   17604 non-null  int64  
 2   rating     17604 non-null  float64
 3   timestamp  17604 non-null  int64  
 4   title      17604 non-null  object 
dtypes: float64(1), int64(3), object(1)
memory usage: 687.8+ KB


In [ ]:
df.isnull().sum()

user_id      0
movie_id     0
rating       0
timestamp    0
title        0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
movies_ratings = df.pivot_table(index='user_id', columns='movie_id', values='rating').fillna(0)
movies_ratings

movie_id  139     568     1900    2284    5985    6244    6674    6683    \
user_id                                                                    
172          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
176          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
221          0.0     0.0     4.5     0.0     0.0     0.0     0.0     0.0   
333          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
339          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...          ...     ...     ...     ...     ...     ...     ...     ...   
283116       0.0     0.0     0.0     5.0     0.0     0.0     0.0     0.0   
283147       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
283175       0.0     0.0     4.5     0.0     0.0     0.0     0.0     0.0   
283188       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
283195       0.0     0.0     4.5     0.0     0.0     0.0     0.0     0.0   

movie_id  8971    27131   ...  190823  191307  191311  191377  192515  192773  \
user_id                   ...                                                   
172          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
176          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
221          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
333          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
339          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...          ...     ...  ...     ...     ...     ...     ...     ...     ...   
283116       0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
283147       0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
283175       0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
283188       0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
283195       0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movie_id  193073  193139  193635  193843  
user_id                                   
172          0.0     0.0     0.0     0.0  
176          0.0     0.0     0.0     0.0  
221          0.0     0.0     0.0     0.0  
333          0.0     0.0     0.0     0.0  
339          0.0     0.0     0.0     0.0  
...          ...     ...     ...     ...  
283116       0.0     0.0     0.0     0.0  
283147       0.0     0.0     0.0     0.0  
283175       0.0     0.0     0.0     0.0  
283188       0.0     0.0     0.0     0.0  
283195       0.0     0.0     0.0     0.0  

[5667 rows x 779 columns]

In [ ]:
user_ratings = movies_ratings.T
user_ratings.head()

user_id   172     176     221     333     339     422     505     516     \
movie_id                                                                   
139          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
568          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1900         0.0     0.0     4.5     0.0     0.0     0.0     0.0     0.0   
2284         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5985         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

user_id   537     540     ...  282784  282853  283000  283054  283095  283116  \
movie_id                  ...                                                   
139          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
568          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
1900         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2284         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     5.0   
5985         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

user_id   283147  283175  283188  283195  
movie_id                                  
139          0.0     0.0     0.0     0.0  
568          0.0     0.0     0.0     0.0  
1900         0.0     4.5     0.0     4.5  
2284         0.0     0.0     0.0     0.0  
5985         0.0     0.0     0.0     0.0  

[5 rows x 5667 columns]

In [ ]:
scaler = StandardScaler()
ratings_scaled = scaler.fit_transform(user_ratings)
ratings_scaled

array([[-0.05042353, -0.03585174, -0.03585174, ..., -0.03585174,
        -0.03585174, -0.05073463],
       [-0.05042353, -0.03585174, -0.03585174, ..., -0.03585174,
        -0.03585174, -0.05073463],
       [-0.05042353, -0.03585174, 27.89265136, ..., 27.89265136,
        -0.03585174, 19.71040334],
       ...,
       [-0.05042353, -0.03585174, -0.03585174, ..., -0.03585174,
        -0.03585174, -0.05073463],
       [-0.05042353, -0.03585174, -0.03585174, ..., -0.03585174,
        -0.03585174, -0.05073463],
       [-0.05042353, -0.03585174, -0.03585174, ..., -0.03585174,
        -0.03585174, -0.05073463]])

In [ ]:
movie_similarity = cosine_similarity(ratings_scaled)
movie_similarity

array([[ 1.        ,  0.01469829, -0.00516548, ..., -0.00496361,
        -0.00481318, -0.0184386 ],
       [ 0.01469829,  1.        ,  0.01429006, ..., -0.02505124,
        -0.02504126, -0.0959622 ],
       [-0.00516548,  0.01429006,  1.        , ..., -0.04171539,
        -0.04175278, -0.16000575],
       ...,
       [-0.00496361, -0.02505124, -0.04171539, ...,  1.        ,
         0.02551427,  0.09782028],
       [-0.00481318, -0.02504126, -0.04175278, ...,  0.02551427,
         1.        ,  0.10189663],
       [-0.0184386 , -0.0959622 , -0.16000575, ...,  0.09782028,
         0.10189663,  1.        ]])

In [ ]:
similarity = pd.DataFrame(movie_similarity, index=user_ratings.index, columns=user_ratings.index)
similarity

movie_id    139       568       1900      2284      5985      6244    \
movie_id                                                               
139       1.000000  0.014698 -0.005165 -0.000400 -0.003369 -0.004746   
568       0.014698  1.000000  0.014290  0.038811 -0.001324  0.012708   
1900     -0.005165  0.014290  1.000000  0.029244  0.004507  0.042145   
2284     -0.000400  0.038811  0.029244  1.000000  0.014996  0.038829   
5985     -0.003369 -0.001324  0.004507  0.014996  1.000000  0.008166   
...            ...       ...       ...       ...       ...       ...   
192773   -0.027030 -0.140215 -0.233760 -0.146374 -0.078426 -0.149726   
193073   -0.015907 -0.075465 -0.125318 -0.078792 -0.038172 -0.080620   
193139   -0.004964 -0.025051 -0.041715 -0.026153 -0.013068 -0.026754   
193635   -0.004813 -0.025041 -0.041753 -0.026141 -0.013997 -0.026740   
193843   -0.018439 -0.095962 -0.160006 -0.100176 -0.053633 -0.102470   

movie_id    6674      6683      8971      27131   ...    190823    191307  \
movie_id                                          ...                       
139       0.004027  0.003473 -0.001802 -0.011422  ... -0.005506 -0.027030   
568      -0.011013  0.004783 -0.002738 -0.020301  ... -0.024524 -0.140215   
1900     -0.013368  0.017181  0.001674 -0.039414  ... -0.040602 -0.233760   
2284     -0.008172  0.021673 -0.000041 -0.021475  ... -0.025608 -0.146374   
5985     -0.006498  0.006712  0.032688 -0.002762  ... -0.013047 -0.078426   
...            ...       ...       ...       ...  ...       ...       ...   
192773    0.045049 -0.091367 -0.105602 -0.108434  ...  0.151581  1.000000   
193073    0.020061 -0.049803 -0.058132  0.158885  ...  0.109389  0.508979   
193139    0.007635 -0.016386 -0.018995 -0.012791  ...  0.025841  0.142293   
193635    0.008089 -0.016311 -0.018846 -0.019279  ...  0.020299  0.148247   
193843    0.031017 -0.062503 -0.072215 -0.073842  ...  0.077831  0.568361   

movie_id    191311    191377    192515    192773    193073    193139  \
movie_id                                                               
139      -0.026658 -0.003117 -0.014092 -0.027030 -0.015907 -0.004964   
568      -0.137487 -0.014669 -0.073423 -0.140215 -0.075465 -0.025051   
1900     -0.229157 -0.024350 -0.122430 -0.233760 -0.125318 -0.041715   
2284     -0.143528 -0.015316 -0.076647 -0.146374 -0.078792 -0.026153   
5985     -0.077007 -0.008404 -0.041025 -0.078426 -0.038172 -0.013068   
...            ...       ...       ...       ...       ...       ...   
192773    0.998470  0.074793  0.435504  1.000000  0.508979  0.142293   
193073    0.512373  0.034578  0.205549  0.508979  1.000000  0.093847   
193139    0.138414  0.012802  0.074958  0.142293  0.093847  1.000000   
193635    0.144247  0.013417  0.078077  0.148247  0.069953  0.025514   
193843    0.553028  0.051441  0.299339  0.568361  0.268206  0.097820   

movie_id    193635    193843  
movie_id                      
139      -0.004813 -0.018439  
568      -0.025041 -0.095962  
1900     -0.041753 -0.160006  
2284     -0.026141 -0.100176  
5985     -0.013997 -0.053633  
...            ...       ...  
192773    0.148247  0.568361  
193073    0.069953  0.268206  
193139    0.025514  0.097820  
193635    1.000000  0.101897  
193843    0.101897  1.000000  

[779 rows x 779 columns]

In [ ]:
def recommend_movies(movie_id, num_recommendations=5):
    
    similarity_movie = similarity[movie_id].sort_values(ascending=False)
    
    similarity_movie = similarity_movie.drop(movie_id)
    
    top_recommendations = similarity_movie.head(num_recommendations)
    
    return top_recommendations

In [ ]:
movies['movie_id'].unique()

array([   139,    568,   1900,   2284,   5985,   6244,   6674,   6683,
         8971,  27131,  27163,  27326,  27362,  27518,  27729,  30905,
        31600,  33688,  34435,  34466,  35828,  36083,  36086,  41650,
        42208,  45036,  46770,  48239,  50279,  51884,  52182,  55098,
        56167,  57183,  58111,  58933,  64650,  69136,  69187,  69269,
        71444,  71460,  71688,  72325,  72587,  72953,  73051,  73170,
        73513,  73881,  73900,  74404,  74406,  74426,  74641,  74787,
        76051,  76056,  76132,  76238,  76241,  76269,  76291,  77210,
        78192,  78196,  78408,  78410,  78488,  78557,  78873,  79195,
        79507,  79838,  79974,  80777,  81087,  81111,  81671,  82097,
        82154,  82902,  82906,  82980,  83004,  83038,  83264,  83266,
        83337,  83339,  83424,  83430,  83457,  83956,  84238,  84500,
        86438,  87882,  88065,  88069,  89554,  89632,  91241,  91250,
        91805,  91844,  93782,  93921,  93923,  94190,  94661,  94663,
      

In [ ]:
movies[movies['movie_id']==27131]

movie_id          title
9     27131  Dil Se (1998)

In [ ]:
movie_id = int(input("Enter the movie ID:"))
recommendation = recommend_movies(movie_id)
print("Recommended items")
for movie_id, similarity in recommendation.items():
    title = movies[movies['movie_id']==movie_id]['title'].values[0] if movie_id in movies['movie_id'].values else "Unknown"
    print(f"{title}")


Recommended items
Khamoshi: The Musical (1996)
No Smoking (2007)
Roja (1992)
Duplicate (1998)
Raavan (2010)
